#!/bin/sh
eth0="enp0s31f6"
eth1="enp4s0"


work()
{
    route del default
    ifconfig ${eth0} up
}

relax()
{
    ifconfig enp0s31f6 down
    route add default gw 10.0.0.1 dev ${eth1}
}

if [[ $1 == "work" ]]; then
    work
    exit 0
fi

if [[ $1 == "relax" ]]; then
    relax
    exit 0
fi
