#!/bin/sh
apt-get update && apt-get upgrade -y

apt-get install silversearcher-ag -y
apt-get install ctags -y
apt-get install cscope -y

# install subl
SUBL_NAME=sublime-text_build-3126_amd64.deb
if ! subl -v > /dev/null
then
    wget https://download.sublimetext.com/${SUBL_NAME} \
    && dpkg -i ${SUBL_NAME}
    if [ $? -eq 0 ]
    then
    :
    else
        echo "can not install sublimetext"
        exit 1
    fi
fi

if [ ! -d sublime-text-imfix ]
then
    git clone https://github.com/lyfeyaj/sublime-text-imfix.git
    cd sublime-text-imfix && ./sublime-imfix
fi
