#!/bin/sh

SUBL_NAME=sublime-text_build-3126_amd64.deb
system_update() {
    apt-get update && apt-get upgrade -y
}
install_cscope_ag() {

    apt-get install silversearcher-ag -y
    apt-get install ctags -y
    apt-get install cscope -y

    echo -e "Bundle \"vim-scripts/autoload_cscope.vim\" \n\
Bundle \"antiagainst/cscope-macros.vim\"" > ~/.vimrc.local
    echo -e "set shiftwidth=8\nset tabstop=8\n\
set softtabstop=8\nset noexpandtab\nset wrap" >> ~/.vimrc.local
    if ! cat ~/.vimrc | grep "source ~/.vimrc.local"
    then
        echo "can not found vimrc.local in vimrc"
        echo "source ~/.vimrc.local" >> ~/.vimrc
    fi
    vim +PluginInstall +qa
}

install_subl() {
    if ! subl -v > /dev/null
    then
        wget https://download.sublimetext.com/${SUBL_NAME} \
        && dpkg -i ${SUBL_NAME}
        if [ $? -eq 0 ]
        then
        :
        else
            echo "can not install sublimetext"
            exit 1
        fi
    fi

    if [ ! -d sublime-text-imfix ]
    then
        git clone https://github.com/lyfeyaj/sublime-text-imfix.git
        cd sublime-text-imfix && ./sublime-imfix
    fi
}

install_32bits_packages() {
    local arch_type=$(uname -m)
    if [[ ${arch_type} == 'x86_64' ]]
    then
        dpkg --add-architecture i386
        apt-get update
        apt-get install gcc-multilib lib32z1-dev lib32ncurses5-dev -y
    fi
}

prepare_ubuntu() {
    echo -e "reconfigure dash==>select no"
    dpkg-reconfigure dash
    apt-get install lib32ncurses5-dev autoconf automake cmake libtool \
    gettext texinfo gawk mtd-utils flex bison -y
}

echo $# $1 $2
if [ $# -eq 0 ]
then
system_update
install_cscope_ag
install_subl
prepare_ubuntu
install_32bits_packages
exit 0
fi

if [ $1 == "sdk" ]
then
prepare_ubuntu
install_32bits_packages
elif [ $1 == "cscope" ]
then
install_cscope_ag
elif [ $1 == "subl" ]
then
install_subl
fi
